import { Member, QuizQuestion, SurveySubmission } from '../types';

export const OLYMPIAN_MEMBERS: Member[] = [
  {
    id: 'zeus-1',
    name: 'Zeus',
    title: 'Ruler of Mount Olympus',
    defaultNickname: 'Thunder Lord',
    code: 'ZEUS01',
    avatarIcon: 'Zap',
    quote: 'Bringing sacred thunder and legendary birthday energy!',
    color: 'from-[#D4AF37] to-[#9A7210]',
  },
  {
    id: 'athena-2',
    name: 'Athena',
    title: 'Goddess of Wisdom & Strategy',
    defaultNickname: 'Wise Owl',
    code: 'ATHENA02',
    avatarIcon: 'Shield',
    quote: 'Only the sharpest answers for our Birthday Hero.',
    color: 'from-[#C89B27] to-[#8C6B1F]',
  },
  {
    id: 'apollo-3',
    name: 'Apollo',
    title: 'God of Sun & Music',
    defaultNickname: 'Golden Sun',
    code: 'APOLLO03',
    avatarIcon: 'Sun',
    quote: 'Radiating golden celebration tunes and good vibes.',
    color: 'from-[#E6B800] to-[#B38F00]',
  },
  {
    id: 'hermes-4',
    name: 'Hermes',
    title: 'Messenger of the Gods',
    defaultNickname: 'Winged Runner',
    code: 'HERMES04',
    avatarIcon: 'Feather',
    quote: 'Delivering birthday wishes at the speed of light!',
    color: 'from-[#B89230] to-[#7A5C10]',
  },
  {
    id: 'hercules-5',
    name: 'Hercules',
    title: 'Hero of Divine Strength',
    defaultNickname: 'Champ',
    code: 'HERC05',
    avatarIcon: 'Dumbbell',
    quote: 'Lifting the birthday hype to legendary levels.',
    color: 'from-[#A87B28] to-[#6E4F10]',
  },
  {
    id: 'artemis-6',
    name: 'Artemis',
    title: 'Guardian of the Moon',
    defaultNickname: 'Silver Archer',
    code: 'ARTEMIS06',
    avatarIcon: 'Moon',
    quote: 'Bullseye accuracy on all trivia questions!',
    color: 'from-[#D8C28A] to-[#9E8548]',
  },
  {
    id: 'poseidon-7',
    name: 'Poseidon',
    title: 'Lord of the Aegean Seas',
    defaultNickname: 'Ocean King',
    code: 'POSEIDON07',
    avatarIcon: 'Waves',
    quote: 'Making grand waves of celebration on Olympus.',
    color: 'from-[#2C3E50] to-[#D4AF37]',
  },
  {
    id: 'aphrodite-8',
    name: 'Aphrodite',
    title: 'Goddess of Love & Charm',
    defaultNickname: 'Radiant Charm',
    code: 'APHRO08',
    avatarIcon: 'Heart',
    quote: 'Spreading warmth, love, and birthday cheer!',
    color: 'from-[#D4AF37] to-[#B8860B]',
  },
  {
    id: 'ares-9',
    name: 'Ares',
    title: 'God of Spirit & Courage',
    defaultNickname: 'Battle Chief',
    code: 'ARES09',
    avatarIcon: 'Flame',
    quote: 'Fierce loyalty and warrior toasts for the Birthday Hero!',
    color: 'from-[#8B5A2B] to-[#D4AF37]',
  },
  {
    id: 'hephaestus-10',
    name: 'Hephaestus',
    title: 'Master Craftsman of Olympus',
    defaultNickname: 'Forge Master',
    code: 'FORGE10',
    avatarIcon: 'Hammer',
    quote: 'Crafting unforgettable golden memories.',
    color: 'from-[#B8860B] to-[#5C4033]',
  },
];

export const SURVEY_QUESTIONS: QuizQuestion[] = [
  // --- SEGMENT I: KNOWLEDGE QUIZ ABOUT THE BIRTHDAY BOY ---
  {
    id: 'q1',
    segment: 1,
    title: 'What is the Birthday Boy’s ultimate superpower skill?',
    subtitle: 'Segment I • Birthday Boy Quiz (Single Choice)',
    type: 'single',
    options: [
      { id: 'q1_a', text: 'Turning caffeine into legendary code & brilliant ideas', isCorrect: true, icon: 'Coffee' },
      { id: 'q1_b', text: 'Sleeping 12 hours without hearing any alarms', isCorrect: false, icon: 'Bed' },
      { id: 'q1_c', text: 'Eating pizza backwards without losing toppings', isCorrect: false, icon: 'Pizza' },
      { id: 'q1_d', text: 'Winning every board game through sheer strategic charm', isCorrect: false, icon: 'Trophy' },
    ],
    explanation: 'Correct! His superpower is turning caffeine into sheer genius ideas and legendary output!',
  },
  {
    id: 'q2',
    segment: 1,
    title: 'Which of these items belong on the Birthday Boy’s Go-To Favorites list?',
    subtitle: 'Segment I • Birthday Boy Quiz (Multiple Choice - Select ALL that apply)',
    type: 'multiple',
    options: [
      { id: 'q2_a', text: 'Late-night chill sessions & deep conversations', isCorrect: true, icon: 'Sparkles' },
      { id: 'q2_b', text: 'Epic weekend road trips & new adventures', isCorrect: true, icon: 'Compass' },
      { id: 'q2_c', text: 'Eating plain raw onions like apples', isCorrect: false, icon: 'Frown' },
      { id: 'q2_d', text: 'Good music, laughter, and high energy vibes', isCorrect: true, icon: 'Music' },
    ],
    explanation: 'Spot on! Late-night chats, epic road trips, and great music are his golden trio!',
  },
  {
    id: 'q3',
    segment: 1,
    title: 'Fill in Yourself: What is the Birthday Boy’s go-to fuel or secret passion?',
    subtitle: 'Segment I • Birthday Boy Quiz (Fill-in-the-blank text input)',
    type: 'text',
    placeholder: 'Type your answer here (e.g., Coffee, Music, Tech, Travel, Laughter)...',
    correctAnswersKeywords: ['coffee', 'music', 'code', 'tech', 'travel', 'laughter', 'pizza', 'gaming', 'sports'],
    explanation: 'Splendid answer! The Birthday Boy thrives on passion, energy, and genuine connection.',
  },
  {
    id: 'q4',
    segment: 1,
    title: 'When the Birthday Boy faces a tough challenge, what is his signature move?',
    subtitle: 'Segment I • Birthday Boy Quiz (Single Choice)',
    type: 'single',
    options: [
      { id: 'q4_a', text: 'Stays cool as ice, cracks a joke, and finds a solution', isCorrect: true, icon: 'Smile' },
      { id: 'q4_b', text: 'Runs into the forest to live with squirrels', isCorrect: false, icon: 'Trees' },
      { id: 'q4_c', text: 'Challenges the problem to a duel at dawn', isCorrect: false, icon: 'Swords' },
      { id: 'q4_d', text: 'Calls Zeus for thunder support', isCorrect: false, icon: 'Zap' },
    ],
    explanation: 'Unstoppable composure! He stays calm, cracks a joke, and delivers results.',
  },

  // --- SEGMENT II: RELATIONSHIP & BIRTHDAY INSIGHTS (No right or wrong answers) ---
  {
    id: 'q5',
    segment: 2,
    title: 'How would you describe your unique relationship with the Birthday Boy?',
    subtitle: 'Segment II • Relationship Insights (No Right or Wrong Answer)',
    type: 'single',
    options: [
      { id: 'q5_a', text: 'Partners in crime - We cause chaotic good everywhere we go!', icon: 'Flame' },
      { id: 'q5_b', text: 'Wisdom Duo - Deep talks, sound advice, and steady support.', icon: 'BookOpen' },
      { id: 'q5_c', text: 'Hype Squad - Non-stop laughter, inside jokes, and high energy.', icon: 'PartyPopper' },
      { id: 'q5_d', text: 'Olympian Alliance - Bound by divine loyalty and trust.', icon: 'Crown' },
    ],
  },
  {
    id: 'q6',
    segment: 2,
    title: 'In your own words: What is a favorite memory or funny moment you shared with him?',
    subtitle: 'Segment II • Relationship Insights (Fill-in-the-blank / Self-fill text)',
    type: 'text',
    placeholder: 'Share a memorable moment, funny story, or inside joke with the Birthday Boy...',
  },
  {
    id: 'q7',
    segment: 2,
    title: 'If you were gifting him an Ancient Olympian Artifact, what would it be?',
    subtitle: 'Segment II • Birthday Gifts & Wishes (Select your favorite)',
    type: 'single',
    options: [
      { id: 'q7_a', text: 'Golden Lyre of Endless Melody & Harmony', icon: 'Music' },
      { id: 'q7_b', text: 'Chalice of Infinite Energy & Good Health', icon: 'Coffee' },
      { id: 'q7_c', text: 'Crown of Victory & Unlimited Success', icon: 'Award' },
      { id: 'q7_d', text: 'Winged Sandals for Infinite Worldwide Adventures', icon: 'Send' },
    ],
  },
  {
    id: 'q8',
    segment: 2,
    title: 'What grand blessing do you wish upon the Birthday Boy for this coming year?',
    subtitle: 'Segment II • Divine Birthday Blessing',
    type: 'single',
    options: [
      { id: 'q8_a', text: 'Boundless health, vitality, and legendary peace of mind', icon: 'ShieldCheck' },
      { id: 'q8_b', text: 'Immense success, prosperity, and golden career triumphs', icon: 'Coins' },
      { id: 'q8_c', text: 'Unforgettable adventures, true love, and joy', icon: 'Sparkles' },
      { id: 'q8_d', text: 'ALL OF THE ABOVE - May Mount Olympus shine upon him!', icon: 'Crown' },
    ],
  },
];

export const INITIAL_SEED_SUBMISSIONS: SurveySubmission[] = [
  {
    id: 'sub-zeus',
    memberId: 'zeus-1',
    nickname: 'Thunder Lord',
    submittedAt: new Date(Date.now() - 3600000 * 5).toISOString(),
    segment1Score: 4,
    segment1MaxScore: 4,
    answers: [
      { questionId: 'q1', selectedOptionIds: ['q1_a'], pointsEarned: 1, maxPoints: 1 },
      { questionId: 'q2', selectedOptionIds: ['q2_a', 'q2_b', 'q2_d'], pointsEarned: 1, maxPoints: 1 },
      { questionId: 'q3', selectedOptionIds: [], textAnswer: 'Endless Coffee & Tech Genius', pointsEarned: 1, maxPoints: 1 },
      { questionId: 'q4', selectedOptionIds: ['q4_a'], pointsEarned: 1, maxPoints: 1 },
      { questionId: 'q5', selectedOptionIds: ['q5_d'] },
      { questionId: 'q6', selectedOptionIds: [], textAnswer: 'That late night road trip where we listened to 90s hits until sunrise!' },
      { questionId: 'q7', selectedOptionIds: ['q7_c'] },
      { questionId: 'q8', selectedOptionIds: ['q8_d'] },
    ],
    relationshipNotes: 'Happy Birthday my brother! May thunder always clear your path to greatness.',
    highScorePrivilege: {
      type: 'request',
      content: 'I request the Birthday Boy to treat the Council to an artisan pizza feast or sing a victory song on video!',
    },
  },
  {
    id: 'sub-athena',
    memberId: 'athena-2',
    nickname: 'Wise Owl',
    submittedAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    segment1Score: 4,
    segment1MaxScore: 4,
    answers: [
      { questionId: 'q1', selectedOptionIds: ['q1_a'], pointsEarned: 1, maxPoints: 1 },
      { questionId: 'q2', selectedOptionIds: ['q2_a', 'q2_b', 'q2_d'], pointsEarned: 1, maxPoints: 1 },
      { questionId: 'q3', selectedOptionIds: [], textAnswer: 'Brilliant Strategy & Laughter', pointsEarned: 1, maxPoints: 1 },
      { questionId: 'q4', selectedOptionIds: ['q4_a'], pointsEarned: 1, maxPoints: 1 },
      { questionId: 'q5', selectedOptionIds: ['q5_b'] },
      { questionId: 'q6', selectedOptionIds: [], textAnswer: 'Debating life philosophies over espresso for hours.' },
      { questionId: 'q7', selectedOptionIds: ['q7_a'] },
      { questionId: 'q8', selectedOptionIds: ['q8_b'] },
    ],
    relationshipNotes: 'Your intellect and kindness inspire everyone on Olympus. Have a golden year!',
    highScorePrivilege: {
      type: 'question',
      content: 'What is your single most ambitious dream or goal for your new age year?',
    },
  },
  {
    id: 'sub-apollo',
    memberId: 'apollo-3',
    nickname: 'Golden Sun',
    submittedAt: new Date(Date.now() - 3600000 * 1).toISOString(),
    segment1Score: 3,
    segment1MaxScore: 4,
    answers: [
      { questionId: 'q1', selectedOptionIds: ['q1_a'], pointsEarned: 1, maxPoints: 1 },
      { questionId: 'q2', selectedOptionIds: ['q2_a', 'q2_d'], pointsEarned: 0.67, maxPoints: 1 },
      { questionId: 'q3', selectedOptionIds: [], textAnswer: 'Music & Great Energy', pointsEarned: 1, maxPoints: 1 },
      { questionId: 'q4', selectedOptionIds: ['q4_a'], pointsEarned: 1, maxPoints: 1 },
      { questionId: 'q5', selectedOptionIds: ['q5_c'] },
      { questionId: 'q6', selectedOptionIds: [], textAnswer: 'Jamming to songs and laughing until our stomachs hurt.' },
      { questionId: 'q7', selectedOptionIds: ['q7_a'] },
      { questionId: 'q8', selectedOptionIds: ['q8_c'] },
    ],
    relationshipNotes: 'May your light shine brighter than the Olympian sun today!',
  },
];
